# Generated by Django 4.1.6 on 2023-02-06 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='userid',
            new_name='prof_id',
        ),
    ]
