# Generated by Django 4.1.6 on 2023-02-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_userid_profile_prof_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
