# Generated by Django 4.1.6 on 2023-02-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.FileField(default='media/defaultprofile.png', upload_to='Upload/ProfilePicture'),
        ),
    ]
