# Generated by Django 4.1.6 on 2023-02-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(default='Upload/ProfilePicture/defaultprofile.png', upload_to='Upload/ProfilePicture'),
        ),
    ]
