# Generated by Django 4.1.6 on 2023-02-08 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, max_length=2000, upload_to='Upload/Posted_Images')),
                ('text', models.CharField(blank=True, max_length=500)),
                ('no_of_likes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
