# Generated by Django 4.1.6 on 2023-02-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_post_userid_alter_post_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
