# Generated by Django 4.1.6 on 2023-02-10 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
