# Generated by Django 4.1.6 on 2023-02-10 11:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_profilepic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0008_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, max_length=2000, upload_to='Upload/Posted_Images')),
                ('text', models.CharField(blank=True, max_length=500)),
                ('no_of_likes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.profile')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
