# Generated by Django 4.1.6 on 2023-02-13 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
